2020-11-05T11:57:18.111713+0300 INFO ------------------------------------
2020-11-05T11:57:18.124706+0300 INFO Application started
2020-11-05T11:57:18.124706+0300 INFO ------------------------------------
2020-11-05T11:57:18.133705+0300 INFO Connection to the database is established.
2020-11-05T11:57:18.136708+0300 INFO Incorrect files are removed
2020-11-05T11:57:18.136708+0300 INFO File search is done
2020-11-05T11:57:18.145706+0300 INFO File is parsed
2020-11-05T11:57:18.272706+0300 INFO Project tables are created if not exist
2020-11-05T11:57:18.272706+0300 INFO Book table is created
2020-11-05T11:57:18.304705+0300 INFO File is parsed
2020-11-05T11:57:18.801702+0300 INFO Project tables are created if not exist
2020-11-05T11:57:18.805810+0300 INFO Book table is created
2020-11-05T11:57:18.832702+0300 INFO File is parsed
2020-11-05T11:57:19.355705+0300 INFO Project tables are created if not exist
2020-11-05T11:57:19.355705+0300 INFO Book table is created
2020-11-05T11:57:19.374739+0300 INFO Connection is closed.
2020-11-05T11:57:19.374739+0300 INFO ------------------------------------
2020-11-05T11:57:19.374739+0300 INFO Application ended
2020-11-05T11:57:19.374739+0300 INFO ------------------------------------
2020-11-05T12:14:48.086901+0300 INFO ------------------------------------
2020-11-05T12:14:48.087902+0300 INFO Application started
2020-11-05T12:14:48.087902+0300 INFO ------------------------------------
2020-11-05T12:14:48.087902+0300 INFO Connection to the database is established.
2020-11-05T12:14:48.089906+0300 INFO Incorrect files are removed
2020-11-05T12:14:48.089906+0300 INFO File search is done
2020-11-05T12:14:48.100902+0300 INFO File is parsed
2020-11-05T12:14:48.464901+0300 INFO Project tables are created if not exist
2020-11-05T12:14:48.464901+0300 INFO Book table is created
2020-11-05T12:14:48.475900+0300 INFO File is parsed
2020-11-05T12:14:48.852901+0300 INFO Project tables are created if not exist
2020-11-05T12:14:48.853903+0300 INFO Book table is created
2020-11-05T12:14:48.856901+0300 INFO File is parsed
2020-11-05T12:14:48.914901+0300 INFO Project tables are created if not exist
2020-11-05T12:14:48.915904+0300 INFO Book table is created
2020-11-05T12:14:48.915904+0300 INFO Connection is closed.
2020-11-05T12:14:48.915904+0300 INFO ------------------------------------
2020-11-05T12:14:48.916902+0300 INFO Application ended
2020-11-05T12:14:48.916902+0300 INFO ------------------------------------
2020-11-05T12:16:49.591799+0300 INFO ------------------------------------
2020-11-05T12:16:49.592799+0300 INFO Application started
2020-11-05T12:16:49.593835+0300 INFO ------------------------------------
2020-11-05T12:16:49.593835+0300 INFO Connection to the database is established.
2020-11-05T12:16:49.595801+0300 INFO Incorrect files are removed
2020-11-05T12:16:49.595801+0300 INFO File search is done
2020-11-05T12:16:49.609795+0300 INFO File is parsed
2020-11-05T12:16:50.006800+0300 INFO Project tables are created if not exist
2020-11-05T12:16:50.006800+0300 INFO Book table is created
2020-11-05T12:16:50.010830+0300 INFO File is parsed
2020-11-05T12:16:50.080796+0300 INFO Project tables are created if not exist
2020-11-05T12:16:50.081796+0300 INFO Book table is created
2020-11-05T12:16:50.094797+0300 INFO File is parsed
2020-11-05T12:16:50.601797+0300 INFO Project tables are created if not exist
2020-11-05T12:16:50.602797+0300 INFO Book table is created
2020-11-05T12:16:50.603798+0300 INFO Connection is closed.
2020-11-05T12:16:50.603798+0300 INFO ------------------------------------
2020-11-05T12:16:50.603798+0300 INFO Application ended
2020-11-05T12:16:50.603798+0300 INFO ------------------------------------
2020-11-05T12:18:33.909046+0300 INFO ------------------------------------
2020-11-05T12:18:33.910047+0300 INFO Application started
2020-11-05T12:18:33.910047+0300 INFO ------------------------------------
2020-11-05T12:18:33.911048+0300 ERROR unable to open database file
2020-11-05T12:18:33.912047+0300 INFO Incorrect files are removed
2020-11-05T12:18:33.913087+0300 INFO File search is done
2020-11-05T12:18:33.916080+0300 INFO File is parsed
2020-11-05T12:18:33.971080+0300 ERROR Cannot create the database connection.
2020-11-05T12:18:33.971080+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (25736), thread 'MainThread' (17232):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 267, in <module>
    main()
    -> <function main at 0x0000028223E28310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 256, in main
    writer.insert_books(book_name, paragraph_cnt, word_count, letters_count, words_with_capital_letter,
    |      |            |          |              |           |              -> '1831'
    |      |            |          |              |           -> '49309'
    |      |            |          |              -> '7994'
    |      |            |          -> '176'
    |      |            -> 'Сонет 17 Уильям Шекспир. - лит. перевод Свами Ранинанда'
    |      -> <function DBWriter.insert_books at 0x0000028223E28040>
    -> <__main__.DBWriter object at 0x0000028223E78A00>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 214, in insert_books
    c = conn.cursor()
        -> None

AttributeError: 'NoneType' object has no attribute 'cursor'
2020-11-05T12:18:33.981079+0300 ERROR Cannot create the database connection.
2020-11-05T12:18:33.981079+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (25736), thread 'MainThread' (17232):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 267, in <module>
    main()
    -> <function main at 0x0000028223E28310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 258, in main
    writer.create_words_frequency_table(conn, book_name, words_dict)
    |      |                            |     |          -> {'сонет': [21, 11], '17': [21, 21], 'уильям': [33, 33], 'шекспир': [50, 50], 'лит': [1, 0], 'перевод': [10, 3], 'свами': [5, ...
    |      |                            |     -> 'Сонет 17 Уильям Шекспир. - лит. перевод Свами Ранинанда'
    |      |                            -> None
    |      -> <function DBWriter.create_words_frequency_table at 0x0000028223E22CA0>
    -> <__main__.DBWriter object at 0x0000028223E78A00>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 183, in create_words_frequency_table
    c = conn.cursor()
        -> None

AttributeError: 'NoneType' object has no attribute 'cursor'
2020-11-05T12:18:33.997048+0300 INFO File is parsed
2020-11-05T12:18:34.556046+0300 ERROR Cannot create the database connection.
2020-11-05T12:18:34.556046+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (25736), thread 'MainThread' (17232):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 267, in <module>
    main()
    -> <function main at 0x0000028223E28310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 256, in main
    writer.insert_books(book_name, paragraph_cnt, word_count, letters_count, words_with_capital_letter,
    |      |            |          |              |           |              -> '10043'
    |      |            |          |              |           -> '309276'
    |      |            |          |              -> '62898'
    |      |            |          -> '2267'
    |      |            -> 'Цветы для Элджернона'
    |      -> <function DBWriter.insert_books at 0x0000028223E28040>
    -> <__main__.DBWriter object at 0x0000028223E78A00>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 214, in insert_books
    c = conn.cursor()
        -> None

AttributeError: 'NoneType' object has no attribute 'cursor'
2020-11-05T12:18:34.558047+0300 ERROR Cannot create the database connection.
2020-11-05T12:18:34.559045+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (25736), thread 'MainThread' (17232):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 267, in <module>
    main()
    -> <function main at 0x0000028223E28310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 258, in main
    writer.create_words_frequency_table(conn, book_name, words_dict)
    |      |                            |     |          -> {'научнофантастический': [1, 1], 'роман': [6, 0], 'американского': [1, 0], 'писателя': [1, 0], 'даниэла': [2, 2], 'киза': [2,...
    |      |                            |     -> 'Цветы для Элджернона'
    |      |                            -> None
    |      -> <function DBWriter.create_words_frequency_table at 0x0000028223E22CA0>
    -> <__main__.DBWriter object at 0x0000028223E78A00>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 183, in create_words_frequency_table
    c = conn.cursor()
        -> None

AttributeError: 'NoneType' object has no attribute 'cursor'
2020-11-05T12:18:34.593046+0300 INFO File is parsed
2020-11-05T12:18:35.014045+0300 ERROR Cannot create the database connection.
2020-11-05T12:18:35.015045+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (25736), thread 'MainThread' (17232):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 267, in <module>
    main()
    -> <function main at 0x0000028223E28310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 256, in main
    writer.insert_books(book_name, paragraph_cnt, word_count, letters_count, words_with_capital_letter,
    |      |            |          |              |           |              -> '10043'
    |      |            |          |              |           -> '309276'
    |      |            |          |              -> '62898'
    |      |            |          -> '2267'
    |      |            -> 'Цветы для Элджернона'
    |      -> <function DBWriter.insert_books at 0x0000028223E28040>
    -> <__main__.DBWriter object at 0x0000028223E78A00>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 214, in insert_books
    c = conn.cursor()
        -> None

AttributeError: 'NoneType' object has no attribute 'cursor'
2020-11-05T12:18:35.020052+0300 ERROR Cannot create the database connection.
2020-11-05T12:18:35.020052+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (25736), thread 'MainThread' (17232):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 267, in <module>
    main()
    -> <function main at 0x0000028223E28310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 258, in main
    writer.create_words_frequency_table(conn, book_name, words_dict)
    |      |                            |     |          -> {'научнофантастический': [1, 1], 'роман': [6, 0], 'американского': [1, 0], 'писателя': [1, 0], 'даниэла': [2, 2], 'киза': [2,...
    |      |                            |     -> 'Цветы для Элджернона'
    |      |                            -> None
    |      -> <function DBWriter.create_words_frequency_table at 0x0000028223E22CA0>
    -> <__main__.DBWriter object at 0x0000028223E78A00>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 183, in create_words_frequency_table
    c = conn.cursor()
        -> None

AttributeError: 'NoneType' object has no attribute 'cursor'
2020-11-05T12:18:35.037045+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (25736), thread 'MainThread' (17232):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 267, in <module>
    main()
    -> <function main at 0x0000028223E28310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 260, in main
    writer.close_connection(conn)
    |      |                -> None
    |      -> <function DBWriter.close_connection at 0x0000028223E225E0>
    -> <__main__.DBWriter object at 0x0000028223E78A00>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 153, in close_connection
    connection.close()
    -> None

AttributeError: 'NoneType' object has no attribute 'close'
2020-11-05T12:18:35.038047+0300 INFO ------------------------------------
2020-11-05T12:18:35.039045+0300 INFO Application ended
2020-11-05T12:18:35.039045+0300 INFO ------------------------------------
2020-11-05T12:18:47.385895+0300 INFO ------------------------------------
2020-11-05T12:18:47.386895+0300 INFO Application started
2020-11-05T12:18:47.386895+0300 INFO ------------------------------------
2020-11-05T12:18:47.387897+0300 ERROR unable to open database file
2020-11-05T12:18:47.389898+0300 INFO Incorrect files are removed
2020-11-05T12:18:47.389898+0300 INFO File search is done
2020-11-05T12:18:47.401894+0300 INFO File is parsed
2020-11-05T12:18:47.865897+0300 ERROR Cannot create the database connection.
2020-11-05T12:18:47.865897+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (12188), thread 'MainThread' (9284):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 267, in <module>
    main()
    -> <function main at 0x000001D9043E8310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 256, in main
    writer.insert_books(book_name, paragraph_cnt, word_count, letters_count, words_with_capital_letter,
    |      |            |          |              |           |              -> '10043'
    |      |            |          |              |           -> '309276'
    |      |            |          |              -> '62898'
    |      |            |          -> '2267'
    |      |            -> 'Цветы для Элджернона'
    |      -> <function DBWriter.insert_books at 0x000001D9043E8040>
    -> <__main__.DBWriter object at 0x000001D904438A00>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 214, in insert_books
    c = conn.cursor()
        -> None

AttributeError: 'NoneType' object has no attribute 'cursor'
2020-11-05T12:18:47.872898+0300 ERROR Cannot create the database connection.
2020-11-05T12:18:47.872898+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (12188), thread 'MainThread' (9284):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 267, in <module>
    main()
    -> <function main at 0x000001D9043E8310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 258, in main
    writer.create_words_frequency_table(conn, book_name, words_dict)
    |      |                            |     |          -> {'научнофантастический': [1, 1], 'роман': [6, 0], 'американского': [1, 0], 'писателя': [1, 0], 'даниэла': [2, 2], 'киза': [2,...
    |      |                            |     -> 'Цветы для Элджернона'
    |      |                            -> None
    |      -> <function DBWriter.create_words_frequency_table at 0x000001D9043E2CA0>
    -> <__main__.DBWriter object at 0x000001D904438A00>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 183, in create_words_frequency_table
    c = conn.cursor()
        -> None

AttributeError: 'NoneType' object has no attribute 'cursor'
2020-11-05T12:18:47.911897+0300 INFO File is parsed
2020-11-05T12:18:48.313897+0300 ERROR Cannot create the database connection.
2020-11-05T12:18:48.313897+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (12188), thread 'MainThread' (9284):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 267, in <module>
    main()
    -> <function main at 0x000001D9043E8310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 256, in main
    writer.insert_books(book_name, paragraph_cnt, word_count, letters_count, words_with_capital_letter,
    |      |            |          |              |           |              -> '10043'
    |      |            |          |              |           -> '309276'
    |      |            |          |              -> '62898'
    |      |            |          -> '2267'
    |      |            -> 'Цветы для Элджернона'
    |      -> <function DBWriter.insert_books at 0x000001D9043E8040>
    -> <__main__.DBWriter object at 0x000001D904438A00>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 214, in insert_books
    c = conn.cursor()
        -> None

AttributeError: 'NoneType' object has no attribute 'cursor'
2020-11-05T12:18:48.317896+0300 ERROR Cannot create the database connection.
2020-11-05T12:18:48.317896+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (12188), thread 'MainThread' (9284):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 267, in <module>
    main()
    -> <function main at 0x000001D9043E8310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 258, in main
    writer.create_words_frequency_table(conn, book_name, words_dict)
    |      |                            |     |          -> {'научнофантастический': [1, 1], 'роман': [6, 0], 'американского': [1, 0], 'писателя': [1, 0], 'даниэла': [2, 2], 'киза': [2,...
    |      |                            |     -> 'Цветы для Элджернона'
    |      |                            -> None
    |      -> <function DBWriter.create_words_frequency_table at 0x000001D9043E2CA0>
    -> <__main__.DBWriter object at 0x000001D904438A00>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 183, in create_words_frequency_table
    c = conn.cursor()
        -> None

AttributeError: 'NoneType' object has no attribute 'cursor'
2020-11-05T12:18:48.337896+0300 INFO File is parsed
2020-11-05T12:18:48.393894+0300 ERROR Cannot create the database connection.
2020-11-05T12:18:48.393894+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (12188), thread 'MainThread' (9284):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 267, in <module>
    main()
    -> <function main at 0x000001D9043E8310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 256, in main
    writer.insert_books(book_name, paragraph_cnt, word_count, letters_count, words_with_capital_letter,
    |      |            |          |              |           |              -> '1831'
    |      |            |          |              |           -> '49309'
    |      |            |          |              -> '7994'
    |      |            |          -> '176'
    |      |            -> 'Сонет 17 Уильям Шекспир. - лит. перевод Свами Ранинанда'
    |      -> <function DBWriter.insert_books at 0x000001D9043E8040>
    -> <__main__.DBWriter object at 0x000001D904438A00>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 214, in insert_books
    c = conn.cursor()
        -> None

AttributeError: 'NoneType' object has no attribute 'cursor'
2020-11-05T12:18:48.397895+0300 ERROR Cannot create the database connection.
2020-11-05T12:18:48.397895+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (12188), thread 'MainThread' (9284):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 267, in <module>
    main()
    -> <function main at 0x000001D9043E8310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 258, in main
    writer.create_words_frequency_table(conn, book_name, words_dict)
    |      |                            |     |          -> {'сонет': [21, 11], '17': [21, 21], 'уильям': [33, 33], 'шекспир': [50, 50], 'лит': [1, 0], 'перевод': [10, 3], 'свами': [5, ...
    |      |                            |     -> 'Сонет 17 Уильям Шекспир. - лит. перевод Свами Ранинанда'
    |      |                            -> None
    |      -> <function DBWriter.create_words_frequency_table at 0x000001D9043E2CA0>
    -> <__main__.DBWriter object at 0x000001D904438A00>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 183, in create_words_frequency_table
    c = conn.cursor()
        -> None

AttributeError: 'NoneType' object has no attribute 'cursor'
2020-11-05T12:18:48.403899+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (12188), thread 'MainThread' (9284):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 267, in <module>
    main()
    -> <function main at 0x000001D9043E8310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 260, in main
    writer.close_connection(conn)
    |      |                -> None
    |      -> <function DBWriter.close_connection at 0x000001D9043E25E0>
    -> <__main__.DBWriter object at 0x000001D904438A00>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 153, in close_connection
    connection.close()
    -> None

AttributeError: 'NoneType' object has no attribute 'close'
2020-11-05T12:18:48.405898+0300 INFO ------------------------------------
2020-11-05T12:18:48.405898+0300 INFO Application ended
2020-11-05T12:18:48.405898+0300 INFO ------------------------------------
2020-11-05T12:18:57.957389+0300 INFO ------------------------------------
2020-11-05T12:18:57.958392+0300 INFO Application started
2020-11-05T12:18:57.958392+0300 INFO ------------------------------------
2020-11-05T12:18:57.958392+0300 ERROR unable to open database file
2020-11-05T12:18:57.960390+0300 INFO Incorrect files are removed
2020-11-05T12:18:57.960390+0300 INFO File search is done
2020-11-05T12:18:57.974391+0300 INFO File is parsed
2020-11-05T12:18:58.367389+0300 ERROR Cannot create the database connection.
2020-11-05T12:18:58.367389+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (27684), thread 'MainThread' (24284):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 267, in <module>
    main()
    -> <function main at 0x0000021876158310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 256, in main
    writer.insert_books(book_name, paragraph_cnt, word_count, letters_count, words_with_capital_letter,
    |      |            |          |              |           |              -> '10043'
    |      |            |          |              |           -> '309276'
    |      |            |          |              -> '62898'
    |      |            |          -> '2267'
    |      |            -> 'Цветы для Элджернона'
    |      -> <function DBWriter.insert_books at 0x0000021876158040>
    -> <__main__.DBWriter object at 0x00000218761A8A00>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 214, in insert_books
    c = conn.cursor()
        -> None

AttributeError: 'NoneType' object has no attribute 'cursor'
2020-11-05T12:18:58.375392+0300 ERROR Cannot create the database connection.
2020-11-05T12:18:58.375392+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (27684), thread 'MainThread' (24284):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 267, in <module>
    main()
    -> <function main at 0x0000021876158310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 258, in main
    writer.create_words_frequency_table(conn, book_name, words_dict)
    |      |                            |     |          -> {'научнофантастический': [1, 1], 'роман': [6, 0], 'американского': [1, 0], 'писателя': [1, 0], 'даниэла': [2, 2], 'киза': [2,...
    |      |                            |     -> 'Цветы для Элджернона'
    |      |                            -> None
    |      -> <function DBWriter.create_words_frequency_table at 0x0000021876152CA0>
    -> <__main__.DBWriter object at 0x00000218761A8A00>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 183, in create_words_frequency_table
    c = conn.cursor()
        -> None

AttributeError: 'NoneType' object has no attribute 'cursor'
2020-11-05T12:18:58.397422+0300 INFO File is parsed
2020-11-05T12:18:58.462392+0300 ERROR Cannot create the database connection.
2020-11-05T12:18:58.462392+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (27684), thread 'MainThread' (24284):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 267, in <module>
    main()
    -> <function main at 0x0000021876158310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 256, in main
    writer.insert_books(book_name, paragraph_cnt, word_count, letters_count, words_with_capital_letter,
    |      |            |          |              |           |              -> '1831'
    |      |            |          |              |           -> '49309'
    |      |            |          |              -> '7994'
    |      |            |          -> '176'
    |      |            -> 'Сонет 17 Уильям Шекспир. - лит. перевод Свами Ранинанда'
    |      -> <function DBWriter.insert_books at 0x0000021876158040>
    -> <__main__.DBWriter object at 0x00000218761A8A00>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 214, in insert_books
    c = conn.cursor()
        -> None

AttributeError: 'NoneType' object has no attribute 'cursor'
2020-11-05T12:18:58.466392+0300 ERROR Cannot create the database connection.
2020-11-05T12:18:58.466392+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (27684), thread 'MainThread' (24284):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 267, in <module>
    main()
    -> <function main at 0x0000021876158310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 258, in main
    writer.create_words_frequency_table(conn, book_name, words_dict)
    |      |                            |     |          -> {'сонет': [21, 11], '17': [21, 21], 'уильям': [33, 33], 'шекспир': [50, 50], 'лит': [1, 0], 'перевод': [10, 3], 'свами': [5, ...
    |      |                            |     -> 'Сонет 17 Уильям Шекспир. - лит. перевод Свами Ранинанда'
    |      |                            -> None
    |      -> <function DBWriter.create_words_frequency_table at 0x0000021876152CA0>
    -> <__main__.DBWriter object at 0x00000218761A8A00>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 183, in create_words_frequency_table
    c = conn.cursor()
        -> None

AttributeError: 'NoneType' object has no attribute 'cursor'
2020-11-05T12:18:58.492391+0300 INFO File is parsed
2020-11-05T12:18:58.896389+0300 ERROR Cannot create the database connection.
2020-11-05T12:18:58.896389+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (27684), thread 'MainThread' (24284):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 267, in <module>
    main()
    -> <function main at 0x0000021876158310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 256, in main
    writer.insert_books(book_name, paragraph_cnt, word_count, letters_count, words_with_capital_letter,
    |      |            |          |              |           |              -> '10043'
    |      |            |          |              |           -> '309276'
    |      |            |          |              -> '62898'
    |      |            |          -> '2267'
    |      |            -> 'Цветы для Элджернона'
    |      -> <function DBWriter.insert_books at 0x0000021876158040>
    -> <__main__.DBWriter object at 0x00000218761A8A00>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 214, in insert_books
    c = conn.cursor()
        -> None

AttributeError: 'NoneType' object has no attribute 'cursor'
2020-11-05T12:18:58.898393+0300 ERROR Cannot create the database connection.
2020-11-05T12:18:58.898393+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (27684), thread 'MainThread' (24284):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 267, in <module>
    main()
    -> <function main at 0x0000021876158310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 258, in main
    writer.create_words_frequency_table(conn, book_name, words_dict)
    |      |                            |     |          -> {'научнофантастический': [1, 1], 'роман': [6, 0], 'американского': [1, 0], 'писателя': [1, 0], 'даниэла': [2, 2], 'киза': [2,...
    |      |                            |     -> 'Цветы для Элджернона'
    |      |                            -> None
    |      -> <function DBWriter.create_words_frequency_table at 0x0000021876152CA0>
    -> <__main__.DBWriter object at 0x00000218761A8A00>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 183, in create_words_frequency_table
    c = conn.cursor()
        -> None

AttributeError: 'NoneType' object has no attribute 'cursor'
2020-11-05T12:18:58.913423+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (27684), thread 'MainThread' (24284):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 267, in <module>
    main()
    -> <function main at 0x0000021876158310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 260, in main
    writer.close_connection(conn)
    |      |                -> None
    |      -> <function DBWriter.close_connection at 0x00000218761525E0>
    -> <__main__.DBWriter object at 0x00000218761A8A00>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 153, in close_connection
    connection.close()
    -> None

AttributeError: 'NoneType' object has no attribute 'close'
2020-11-05T12:18:58.914423+0300 INFO ------------------------------------
2020-11-05T12:18:58.914423+0300 INFO Application ended
2020-11-05T12:18:58.915426+0300 INFO ------------------------------------
2020-11-05T12:19:47.677899+0300 INFO ------------------------------------
2020-11-05T12:19:47.678900+0300 INFO Application started
2020-11-05T12:19:47.678900+0300 INFO ------------------------------------
2020-11-05T12:19:47.679935+0300 INFO Connection to the database is established.
2020-11-05T12:19:47.680935+0300 INFO Incorrect files are removed
2020-11-05T12:19:47.681901+0300 INFO File search is done
2020-11-05T12:19:47.694899+0300 INFO File is parsed
2020-11-05T12:19:48.109902+0300 INFO Project tables are created if not exist
2020-11-05T12:19:48.121898+0300 INFO Book table is created
2020-11-05T12:19:48.187904+0300 INFO File is parsed
2020-11-05T12:19:48.573898+0300 INFO Project tables are created if not exist
2020-11-05T12:19:48.574902+0300 INFO Book table is created
2020-11-05T12:19:48.576898+0300 INFO File is parsed
2020-11-05T12:19:48.627898+0300 INFO Project tables are created if not exist
2020-11-05T12:19:48.641898+0300 INFO Book table is created
2020-11-05T12:19:48.660908+0300 INFO Connection is closed.
2020-11-05T12:19:48.660908+0300 INFO ------------------------------------
2020-11-05T12:19:48.660908+0300 INFO Application ended
2020-11-05T12:19:48.660908+0300 INFO ------------------------------------
2020-11-05T12:23:47.897214+0300 INFO ------------------------------------
2020-11-05T12:23:47.898248+0300 INFO Application started
2020-11-05T12:23:47.898248+0300 INFO ------------------------------------
2020-11-05T12:23:47.899217+0300 INFO Connection to the database is established.
2020-11-05T12:23:47.899217+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (8476), thread 'MainThread' (18744):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 267, in <module>
    main()
    -> <function main at 0x000001EE1BB98310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 244, in main
    for fb2_file in reader.fb2_file_search():
                    |      -> <function Fb2Reader.fb2_file_search at 0x000001EE1BB8C040>
                    -> <__main__.Fb2Reader object at 0x000001EE1BBE8A30>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 17, in fb2_file_search
    os.chdir('/res/input')
    |  -> <built-in function chdir>
    -> <module 'os' from 'C:\\Users\\Krystsina_Bahdanava\\AppData\\Local\\Programs\\Python\\Python38\\lib\\os.py'>

FileNotFoundError: [WinError 3] The system cannot find the path specified: '/res/input'
2020-11-05T12:23:47.906217+0300 ERROR An error has been caught in function '<module>', process 'MainProcess' (8476), thread 'MainThread' (18744):
Traceback (most recent call last):

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 267, in <module>
    main()
    -> <function main at 0x000001EE1BB98310>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 244, in main
    for fb2_file in reader.fb2_file_search():
                    |      -> <function Fb2Reader.fb2_file_search at 0x000001EE1BB8C040>
                    -> <__main__.Fb2Reader object at 0x000001EE1BBE8A30>

TypeError: 'NoneType' object is not iterable
2020-11-05T12:27:55.889701+0300 INFO ------------------------------------
2020-11-05T12:27:55.890704+0300 INFO Application started
2020-11-05T12:27:55.890704+0300 INFO ------------------------------------
2020-11-05T12:27:55.891703+0300 INFO Connection to the database is established.
2020-11-05T12:27:55.893704+0300 INFO Incorrect files are removed
2020-11-05T12:27:55.893704+0300 INFO File search is done
2020-11-05T12:27:55.907703+0300 INFO File is parsed
2020-11-05T12:27:56.484701+0300 INFO Project tables are created if not exist
2020-11-05T12:27:56.485701+0300 INFO Book table is created
2020-11-05T12:27:56.500700+0300 INFO File is parsed
2020-11-05T12:27:56.944700+0300 INFO Project tables are created if not exist
2020-11-05T12:27:56.945701+0300 INFO Book table is created
2020-11-05T12:27:56.950703+0300 INFO File is parsed
2020-11-05T12:27:57.023701+0300 INFO Project tables are created if not exist
2020-11-05T12:27:57.024704+0300 INFO Book table is created
2020-11-05T12:27:57.024704+0300 INFO Connection is closed.
2020-11-05T12:27:57.025704+0300 INFO ------------------------------------
2020-11-05T12:27:57.025704+0300 INFO Application ended
2020-11-05T12:27:57.025704+0300 INFO ------------------------------------
2020-11-05T12:38:00.167761+0300 INFO ------------------------------------
2020-11-05T12:38:00.168761+0300 INFO Application started
2020-11-05T12:38:00.168761+0300 INFO ------------------------------------
2020-11-05T12:38:00.168761+0300 INFO Connection to the database is established.
2020-11-05T12:38:00.173763+0300 DEBUG accommodation.csv is moved to the incorrect_input folder
2020-11-05T12:38:00.173763+0300 INFO Incorrect files are removed
2020-11-05T12:38:00.173763+0300 INFO File search is done
2020-11-05T12:38:00.186762+0300 INFO File is parsed
2020-11-05T12:38:00.580764+0300 INFO Project tables are created if not exist
2020-11-05T12:38:00.595769+0300 INFO Book table is created
2020-11-05T12:38:00.645761+0300 INFO File is parsed
2020-11-05T12:38:00.707762+0300 INFO Project tables are created if not exist
2020-11-05T12:38:00.728762+0300 INFO Book table is created
2020-11-05T12:38:00.759760+0300 INFO File is parsed
2020-11-05T12:38:01.154759+0300 INFO Project tables are created if not exist
2020-11-05T12:38:01.154759+0300 INFO Book table is created
2020-11-05T12:38:01.156762+0300 INFO Connection is closed.
2020-11-05T12:38:01.156762+0300 INFO ------------------------------------
2020-11-05T12:38:01.157763+0300 INFO Application ended
2020-11-05T12:38:01.157763+0300 INFO ------------------------------------
2020-11-05T13:03:44.742701+0300 INFO ------------------------------------
2020-11-05T13:03:44.742701+0300 INFO Application started
2020-11-05T13:03:44.743705+0300 INFO ------------------------------------
2020-11-05T13:03:44.743705+0300 INFO Connection to the database is established.
2020-11-05T13:03:44.745674+0300 INFO Incorrect files are removed
2020-11-05T13:03:44.745674+0300 INFO File search is done
2020-11-05T13:03:44.759706+0300 INFO File is parsed
2020-11-05T13:03:44.760674+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (11600), thread 'MainThread' (35676):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 268, in <module>
    main()
    -> <function main at 0x000001E6FFF68310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 250, in main
    paragraph_cnt = str(file_service.count_paragraph(tree))
                        |            |               -> <xml.etree.ElementTree.ElementTree object at 0x000001E6FFFB8D00>
                        |            -> <function FileService.count_paragraph at 0x000001E6FFF5CA60>
                        -> <__main__.FileService object at 0x000001E6FFE82070>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 55, in count_paragraph
    logger.debug("Number of paragraphs: " + cnt_par_all)
    |      |                                -> 2267
    |      -> <function Logger.debug at 0x000001E6FFF37A60>
    -> <loguru.logger handlers=[(id=0, level=10, sink=<stderr>), (id=1, level=10, sink='debug.log')]>

TypeError: can only concatenate str (not "int") to str
2020-11-05T13:03:45.153669+0300 INFO Project tables are created if not exist
2020-11-05T13:03:45.153669+0300 INFO Book table is created
2020-11-05T13:03:45.165669+0300 INFO File is parsed
2020-11-05T13:03:45.166670+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (11600), thread 'MainThread' (35676):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 268, in <module>
    main()
    -> <function main at 0x000001E6FFF68310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 250, in main
    paragraph_cnt = str(file_service.count_paragraph(tree))
                        |            |               -> <xml.etree.ElementTree.ElementTree object at 0x000001E6FFE820A0>
                        |            -> <function FileService.count_paragraph at 0x000001E6FFF5CA60>
                        -> <__main__.FileService object at 0x000001E6FFE69430>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 55, in count_paragraph
    logger.debug("Number of paragraphs: " + cnt_par_all)
    |      |                                -> 2267
    |      -> <function Logger.debug at 0x000001E6FFF37A60>
    -> <loguru.logger handlers=[(id=0, level=10, sink=<stderr>), (id=1, level=10, sink='debug.log')]>

TypeError: can only concatenate str (not "int") to str
2020-11-05T13:03:45.565670+0300 INFO Project tables are created if not exist
2020-11-05T13:03:45.565670+0300 INFO Book table is created
2020-11-05T13:03:45.568669+0300 INFO File is parsed
2020-11-05T13:03:45.569668+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (11600), thread 'MainThread' (35676):
Traceback (most recent call last):

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 268, in <module>
    main()
    -> <function main at 0x000001E6FFF68310>

> File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 250, in main
    paragraph_cnt = str(file_service.count_paragraph(tree))
                        |            |               -> <xml.etree.ElementTree.ElementTree object at 0x000001E6FFF65A60>
                        |            -> <function FileService.count_paragraph at 0x000001E6FFF5CA60>
                        -> <__main__.FileService object at 0x000001E6FFF65970>

  File "C:/Users/Krystsina_Bahdanava/PycharmProjects/fb2Reader/main.py", line 55, in count_paragraph
    logger.debug("Number of paragraphs: " + cnt_par_all)
    |      |                                -> 176
    |      -> <function Logger.debug at 0x000001E6FFF37A60>
    -> <loguru.logger handlers=[(id=0, level=10, sink=<stderr>), (id=1, level=10, sink='debug.log')]>

TypeError: can only concatenate str (not "int") to str
2020-11-05T13:03:45.620703+0300 INFO Project tables are created if not exist
2020-11-05T13:03:45.621672+0300 INFO Book table is created
2020-11-05T13:03:45.621672+0300 INFO Connection is closed.
2020-11-05T13:03:45.622709+0300 INFO ------------------------------------
2020-11-05T13:03:45.622709+0300 INFO Application ended
2020-11-05T13:03:45.622709+0300 INFO ------------------------------------
2020-11-05T13:03:59.953582+0300 INFO ------------------------------------
2020-11-05T13:03:59.954583+0300 INFO Application started
2020-11-05T13:03:59.954583+0300 INFO ------------------------------------
2020-11-05T13:03:59.955585+0300 INFO Connection to the database is established.
2020-11-05T13:03:59.957584+0300 INFO Incorrect files are removed
2020-11-05T13:03:59.957584+0300 INFO File search is done
2020-11-05T13:03:59.970584+0300 INFO File is parsed
2020-11-05T13:03:59.971587+0300 DEBUG Number of paragraphs: 2267
2020-11-05T13:04:00.433582+0300 INFO Project tables are created if not exist
2020-11-05T13:04:00.434583+0300 INFO Book table is created
2020-11-05T13:04:00.438582+0300 INFO File is parsed
2020-11-05T13:04:00.439582+0300 DEBUG Number of paragraphs: 176
2020-11-05T13:04:00.512582+0300 INFO Project tables are created if not exist
2020-11-05T13:04:00.512582+0300 INFO Book table is created
2020-11-05T13:04:00.523582+0300 INFO File is parsed
2020-11-05T13:04:00.524585+0300 DEBUG Number of paragraphs: 2267
2020-11-05T13:04:00.937584+0300 INFO Project tables are created if not exist
2020-11-05T13:04:00.937584+0300 INFO Book table is created
2020-11-05T13:04:00.938588+0300 INFO Connection is closed.
2020-11-05T13:04:00.938588+0300 INFO ------------------------------------
2020-11-05T13:04:00.938588+0300 INFO Application ended
2020-11-05T13:04:00.938588+0300 INFO ------------------------------------
2020-11-05T14:06:58.841841+0300 INFO ------------------------------------
2020-11-05T14:06:58.848218+0300 INFO Application started
2020-11-05T14:06:58.848894+0300 INFO ------------------------------------
2020-11-05T14:06:58.857771+0300 INFO Connection to the database is established.
2020-11-05T14:06:58.862772+0300 INFO Incorrect files are removed
2020-11-05T14:06:58.865773+0300 INFO File search is done
2020-11-05T14:06:58.876771+0300 INFO File is parsed
2020-11-05T14:06:58.876853+0300 DEBUG Number of paragraphs: 176
2020-11-05T14:06:59.084770+0300 INFO Project tables are created if not exist
2020-11-05T14:06:59.086769+0300 INFO Book table is created
2020-11-05T14:06:59.124770+0300 INFO File is parsed
2020-11-05T14:06:59.126768+0300 DEBUG Number of paragraphs: 2267
2020-11-05T14:07:00.139661+0300 INFO Project tables are created if not exist
2020-11-05T14:07:00.140787+0300 INFO Book table is created
2020-11-05T14:07:00.161681+0300 INFO File is parsed
2020-11-05T14:07:00.163398+0300 DEBUG Number of paragraphs: 2267
2020-11-05T14:07:00.811786+0300 INFO Project tables are created if not exist
2020-11-05T14:07:00.811786+0300 INFO Book table is created
2020-11-05T14:07:00.812785+0300 INFO Connection is closed.
2020-11-05T14:07:00.813697+0300 INFO ------------------------------------
2020-11-05T14:07:00.814211+0300 INFO Application ended
2020-11-05T14:07:00.814695+0300 INFO ------------------------------------
2020-11-05T17:02:14.570889+0300 INFO ------------------------------------
2020-11-05T17:02:14.576862+0300 INFO Application started
2020-11-05T17:02:14.577863+0300 INFO ------------------------------------
2020-11-05T17:02:14.584872+0300 INFO Connection to the database is established.
2020-11-05T17:02:14.586875+0300 INFO Incorrect files are removed
2020-11-05T17:02:14.588876+0300 INFO File search is done
2020-11-05T17:02:14.602873+0300 INFO File is parsed
2020-11-05T17:02:14.606876+0300 DEBUG Number of paragraphs: 2267
2020-11-05T17:02:15.044874+0300 INFO Project tables are created if not exist
2020-11-05T17:02:15.047876+0300 INFO Book table is created
2020-11-05T17:02:15.058181+0300 INFO File is parsed
2020-11-05T17:02:15.060178+0300 DEBUG Number of paragraphs: 176
2020-11-05T17:02:15.111209+0300 INFO Project tables are created if not exist
2020-11-05T17:02:15.114178+0300 INFO Book table is created
2020-11-05T17:02:15.130305+0300 INFO File is parsed
2020-11-05T17:02:15.134306+0300 DEBUG Number of paragraphs: 2267
2020-11-05T17:02:15.491308+0300 INFO Project tables are created if not exist
2020-11-05T17:02:15.494306+0300 INFO Book table is created
2020-11-05T17:02:15.496307+0300 INFO Connection is closed.
2020-11-05T17:02:15.497306+0300 INFO ------------------------------------
2020-11-05T17:02:15.498306+0300 INFO Application ended
2020-11-05T17:02:15.499306+0300 INFO ------------------------------------
